### ISSUE TITLE
2.1.2 causes npm to fail when installing gifsicle, jpegtran and opti-png 

### ISSUE THREAD

**Issue by stuartmemo** [kevva/bin-build#6]
I'm not sure of the actual issue, just wanted to [flag up this](https://github.com/npm/npm/issues/8682) to see if it's something you can help with. Thanks!

**Comment by hockenmaier** [comment]
We had the same issue; gifsicle and optipng were failing to install using 2.1.2.  We exhausted all other options that could be cause of this issue, but the only thing that worked was downgrading bin-build to 2.1.1.

**Comment by shinnn** [comment]
This problem would be fixed when https://github.com/kevva/download/issues/64 is fixed.

**Comment by jmorille** [comment]
The best thing for this problem should be to not use direct donwload but the npm download mechanism (like optional dependencies) in order to use the npm configuration like corporate npm registry.

This change permit to cache in local (thank to product like Sonatype Nexus) useful when you have many developpers and respect some developpement constraint like BCP (Business Continuity Planning) or DRP ( Disaster Recovery Plan) that assurance or bank have to respect.

**Comment by marc-guenther** [comment]
mikeal/tunnel-agent#15 fixed this problem for us.

**Comment by marc-guenther** [comment]
which has just been released as 0.4.2 :)
